version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: America/New_York

  - package-ecosystem: npm
    directory: '/'
    versioning-strategy: increase
    schedule:
      interval: weekly
      time: '04:00'
      timezone: America/New_York
    groups:
      prod-major:
        dependency-type: production
        update-types:
          - 'major'
      prod-minor:
        dependency-type: production
        update-types:
          - 'minor'
          - 'patch'
      dev-major:
        dependency-type: development
        update-types:
          - 'major'
      dev-minor:
        dependency-type: development
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
