name: Lint & Test

on:
  push:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      node: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: get-version
        run: echo "::set-output name=version::$(grep -oP 'FROM node:\K\d+' Dockerfile)"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.prepare.outputs.node }}'
          cache: yarn
      - name: Test
        run: |
          yarn install
          yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.prepare.outputs.node }}'
          cache: yarn
      - name: Lint
        run: |
          yarn install
          yarn lint
