name: Lint & Test

on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Build
        run: |
          yarn install --immutable
          yarn build
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: built
          path: .svelte-kit
          include-hidden-files: true

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: built
          path: .svelte-kit
      - name: Test
        run: |
          yarn install --immutable
          yarn sync
          yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: built
          path: .svelte-kit
      - name: Lint
        run: |
          yarn install --immutable
          yarn sync
          yarn lint:ci
